list = {
"Hollow Knight",
"Dead Cell",
"Enter the Gungeon",
"Darkest Dungeon",
"10 Minutes Till Dawn",
"Don't Starve",
"Sanabi",
"Katana ZERO",
"The Binding of Isaac",
"Hades",
"Noita",
"Ori and the will of the wisps",
"Stardew Valley",
"Terraria",
"Undertale",
"Potion Craft",
"RimWorld",
"Helltaker",
"Sid Meier's Civilization VI",
"Slay the Spire",
"Stellaris",
"千恋万花",
"Song of Saya",
"Darkwood",
"Disco Elysium",
"Divinity: Original Sin 2",
"Gris",
"Spiritfarer",
"To the Moon",
"Hotline Miami",
"Plant vs Zombies",
"Solar2",
"Stacklands",
"Wallpaper Engine",
"Rain World",
"Elden Ring",
"Cuphead",
"Bad North",
}